project_python/website/item/urls.py
from django.urls import path

from . import views

app_name = "item"

urlpatterns=[
    path('<int:pk>/',views.detail, name='detail'),
]

project_python/website/website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from core.views import index, contact, about, policy, terms,  sign

urlpatterns = [
    path('',index, name='index'),
    path('items/', include('item.urls')),
    path('contact/', contact, name='contact'),
    path('About/', about, name='about'),
    path('Privacy Policy/', policy, name='policy'),
    path('signup/', sign ,name='sign'),
    path('Terms/', terms, name='terms'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project_python/website/core/models.py
from django.db import models

# Create your models here.

project_python/website/item/models.py
from django.contrib.auth.models import User

from django.db import models

class Category(models.Model):
    name= models.CharField(max_length=225)
    
    class Meta:
        ordering = ('name',)
        verbose_name_plural='Categories'
        
    def __str__(self):
        return self.name
    
class Item(models.Model):
    Category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    name= models.CharField(max_length=225)     
    
    def __str__(self):
        return self.name
class Books(models.Model):
    Item = models.ForeignKey(Item, related_name='books', on_delete=models.CASCADE)
    name= models.CharField(max_length=225)    
    description = models.TextField(blank=True, null=True)
    price = models.FloatField()
    image = models.ImageField(upload_to='item_images', blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name
    

project_python/website/core/views.py
from django.shortcuts import render

from item.models import Category, Item, Books
# Create your views here.
def index(request):
    items = Books.objects.filter(is_sold=False)[:]
    categories = Category.objects.all()[:]
    return render(request,'core/index.html',{
        'categories': categories,
        'items' :items,
    })

def contact(request):
    return render(request,'core/contact.html')

def about(request):
    return render(request,'core/about.html')

def policy(request):
    return render(request,'core/policy.html')

def terms(request):
    return render(request,'core/terms.html')

def sign(request):
    return render(request,'core/signup.html')

project_python/website/item/views.py
from django.shortcuts import render, get_object_or_404

from .models import Books

def detail(request, pk):
    item = get_object_or_404(Books, pk=pk)
    
    return render(request, 'item/detail.html',{
        'item': item
    })

project_python/website/core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock title %}

{% block content %}
<h1>The about page</h1>
{% endblock content %}

project_python/website/core/templates/core/base.html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock title %} | EEC Library
        </title>
    </head>

    <body>
        <nav class="py-6 px-6 flex justify-between items-center border-b border-grey-200">
            <a href="/" class="text-xl font-semibold">EEC Library</a>
            <Input type ="text" name = "Search_data" class="py-2 px-3 bg-gray-200 rounded-xl text-lg font-semibold border-b border-r border-l border-t border-black" size=75>
            <a href="#" class="text-lg font-semibold hover:text-gery-500">Browse</a>
            <div class="space-x-6">
                <a href="{% url 'sign' %}" class="px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">sign up</a>
                <a href="#" class="px-6 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">login</a>
            </div>
        </nav>
        <div class="px-6 py-6">
             {% block content%}{% endblock content%}
        </div>
        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>
                <p class="text-lg text-gray-500">for more information contact the admin</p>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>
                <ul class="space-y-2">
                    <li><a href="{% url 'about' %}" class="text-lg text-teal-500 hover:text-teal-700">About</a></li>
                    <li><a href="{% url 'contact' %}" class="text-lg text-teal-500 hover:text-teal-700">contact</a></li>
                    <li><a href="{% url 'policy' %}" class="text-lg text-teal-500 hover:text-teal-700">Privacy policy</a></li>
                    <li><a href="{% url 'terms' %}" class="text-lg text-teal-500 hover:text-teal-700">term of use</a></li>
                </ul>
            </div>
        </footer>
    </body>
</html>

project_python/website/core/templates/core/contact.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock title %}

{% block content %}
<h1>The contact page</h1>
{% endblock content %}

project_python/website/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock title %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-left">Newest Books</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for item in items %}
        <div>
            <a href="{% url 'item:detail' item.id %}">
                <div>
                    <img src="{{ item.image.url}}" class="rounded-t-xl">
                </div>
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{ item.name }}</h2>
                    <p class="text-gray-500">Price: {{item.price}}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-left">Categories</h2>
    <div class="grid grid-cols-3 gap-3">
        {% for category in categories %}
        <div>
            <a href="#">
                <div class="p-6 bg-white rounded-b-xl">
                    <h2 class="text-2xl">{{ category.name }}</h2>
                    <p class="text-gray-500">{{category.items.count}} items</p>
                </div>
            </a>
        </div>
        {% endfor %}    
    </div>
</div>
{% endblock content %}

project_python/website/core/templates/core/policy.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock title %}

{% block content %}
<h1>The Privacy policy page</h1>
{% endblock content %}

project_python/website/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock title %}

{% block content %}
<h1>The signup page</h1>
{% endblock content %}

project_python/website/core/templates/core/terms.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock title %}

{% block content %}
<h1>The term of use page</h1>
{% endblock content %}

project_python/website/item/templates/item/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ item.name }}{% endblock title %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-3">
        <img src="{{item.image.url}}" class="rounded-xl">
    </div>
    <div class="col-span-2 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ item.name}}</h1>
        <p class="text-gray-500"><strong>Price: </strong>{{ item.price}}</p>
        <p class="text-gray-500"><strong>Seller: </strong>{{ item.created_by.username}}</p>
        {% if item.description %}
        <p class="text-gray-700">
            <strong class="text-gray-500">Description:</strong><br>
            {{ item.description }}
        </p>
        {% endif %}

        <a href="#" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Buy</a>
</div>
{% endblock content %}